### ISSUE TITLE
EPIC: Board page

### ISSUE THREAD

**Issue by 4rgc** [4rgc/trellzo-web#25]
This is an EPIC for all tickets related to the Board page.

This contains all the issues that need to be resolved before the Board page can be deemed complete for the ETP.
- [ ] Display Lists
- [ ] Display Notes inside Lists
- [ ] Move Notes between Lists
- [ ] Add Lists
- [ ] Add Notes to Lists
- [ ] Remove Lists
- [ ] Rename Lists
- [ ] Delete a Board
